spring.application.name=demo
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/drawing_app
spring.datasource.username=postgres
spring.datasource.password=riturajani11

## Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

#jwt properties
security.jwt.secret-key=7e90019ceda2668e753e11125b32d90cfb02696057044ade5c7b59ba88afad14
# 1h in millisecond
security.jwt.expiration-time=3600000
logging.level.org.springframework.security=DEBUG